language: ruby

rvm:
  - 2.2.2
  - 2.3.1
  - 2.4.1
  - ruby-head
  - jruby-9.1.8.0
  - jruby-head

gemfile:
  - Gemfile

services:
- mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
