language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2
  - 2.3.1
  - rbx-2.2.10
  - jruby-19mode

env:
  - MONGOID_VERSION=4.0
  - MONGOID_VERSION=5.0
  - MONGOID_VERSION=HEAD

services:
  - mongodb
